# 버전 정보
version: 0.2

# 빌드 단계를 정의
phases:
  # 빌드 전 단계
  pre_build:
    commands:
      - npm install  # npm을 이용하여 필요한 패키지들을 설치

  # 빌드 단계
  build:
    commands:
      - npm run build  # npm 스크립트를 통해 빌드 수행

  # 빌드 후 단계
  post_build:
    commands:
      - aws s3 sync build/ s3://mju-team2  # S3 버킷에 빌드 결과물 업로드
      - aws cloudfront create-invalidation --distribution-id E35SMWI18LDN6Q --paths "/*"  # CloudFront 캐시 무효화

# 빌드 후 생성된 결과물에 대한 정보
artifacts:
  files:
    - '**/*'  # 모든 파일과 디렉토리를 포함
  base-directory: build  # 결과물이 위치한 기본 디렉토리는 'build'
