version: 0.2

phases:
  pre_build:
    commands:
      - npm install  # 필요한 패키지 설치
  build:
    commands:
      - npm run build  # 빌드 실행
  post_build:
    commands:
      - aws s3 sync ./build s3://mju-team2 --delete  # S3 버킷으로 빌드 결과물 업로드
      - aws cloudfront create-invalidation --distribution-id E35SMWI18LDN6Q --paths "/*"  # CloudFront 캐시 무효화

artifacts:
  files:
    - '**/*'  # 모든 파일과 디렉토리 포함
  base-directory: build  # 결과물 기본 디렉토리
